const TO_STANDARD = {
  ts: 'TypeScript',
  typescript: 'TypeScript',
  typescrit: 'TypeScript',
  typesciprt: 'TypeScript',
  typscript: 'TypeScript',
  typsciprt: 'TypeScript',
  tsx: 'TypeScript',
  javascript: 'JavaScript',
  js: 'JavaScript',
  javscript: 'JavaScript',
  javasript: 'JavaScript',
  jscript: 'JavaScript',
  next: 'Next.js',
  nextjs: 'Next.js',
  'next.js': 'Next.js',
  'next-js': 'Next.js',
  'Next.js': 'Next.js',
  'Next-js': 'Next.js',
  nextj: 'Next.js',
  nest: 'NestJS',
  nestjs: 'NestJS',
  'nest.js': 'NestJS',
  'nest-js': 'NestJS',
  node: 'NodeJS',
  nodejs: 'NodeJS',
  'node.js': 'NodeJS',
  'node-js': 'NodeJS',
  nodej: 'NodeJS',
  react: 'React',
  reactjs: 'React',
  'react.js': 'React',
  'react-js': 'React',
  reactj: 'React',
  flutter: 'Flutter',
  fluter: 'Flutter',
  dart: 'Dart',
  firebase: 'Firebase',
  'fire-base': 'Firebase',
  'firebase.js': 'Firebase',
  redis: 'Redis',
  mysql: 'MySQL',
  'my-sql': 'MySQL',
  my_sql: 'MySQL',
  python: 'Python',
  py: 'Python',
  python3: 'Python',
  numpy: 'NumPy',
  numpi: 'NumPy',
  pygame: 'Pygame',
  'py-game': 'Pygame',
  java: 'Java',
  c: 'C',
  cpp: 'C++',
  'c++': 'C++',
  'c-plus-plus': 'C++',
  html: 'HTML',
  html5: 'HTML5',
  css: 'CSS',
  css3: 'CSS3',
  git: 'Git',
  github: 'GitHub',
  'git-hub': 'GitHub',
};

export function normalizeStackToken(token) {
  if (!token || typeof token !== 'string') return token || '';
  const key = token.trim().toLowerCase();
  return TO_STANDARD[key] ?? token.trim();
}

export default normalizeStackToken;
